name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: build
      uses: actions/setup-node@v3
      with:
        node-version: '18.2.0'
        cache: 'npm'
    - run: npm ci
    - run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@master
      with:
        name: build-files
        path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: build-files
          path: ./build
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Upload to S3
        run: aws s3 cp ./build/ s3://${{ secrets.AWS_BUCKET_NAME }}
        

      

    
